project:
  type: website

website:
  title: "Li Yong Pan"
  site-url: https://blog.panliyong.nl
  description: "Personal blog of Li Yong Pan"
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/liyongg
      - icon: linkedin
        href: https://www.linkedin.com/in/panliyong/
format:
  html:
    theme: 
      dark: darkly
      light: cosmo
    css: styles.css

comments: 
  giscus: 
    repo: liyongg/blog

author: "Li Yong Pan"
