project:
  type: website

website:
  title: "Li Yong Pan"
  site-url: https://blog.panliyong.nl
  description: "Personal blog of Li Yong Pan"
  favicon: handsign.svg
  google-analytics: G-HBT8Z7VKEK
  navbar:
    logo: handsign.svg
    right:
      - icon: journal-code
        text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/liyongg
      - icon: linkedin
        href: https://www.linkedin.com/in/panliyong/
format:
  html:
    theme: 
      dark: darkly
      light: cosmo
    css: styles.css

comments: 
  giscus: 
    repo: liyongg/blog
