---
title: "What to Expect from this Blog"
date: "2024-01-09"
categories: [news]
comments: false
description: Tempering Expectations
image: ../media/missing.svg
---

On the 9th of January 2024 I decided to start a blog to document small hobby projects publicly.
At around 11:40 PM (the time I am usuallly most active with projects like these), I was able to launch the blog successfully using [Netlify](https://www.netlify.com/) and [Quarto](https://quarto.org/), combined with my custom (sub)domain [blog.panliyong.nl](https://blog.panliyong.nl).
The repository is hosted on GitHub and uses GitHub Actions to update the website automatically on every push to the `main` branch.

The current idea of this blog is to write about small personal projects to illustrate proficiency of techniques and applications in primarily data science and web development.
However, there might also be some one-off useful tips and tricks that I would like to post here.
I have a few ideas in mind and will try to showcase them in upcoming blog posts.
Now, after setting up the [landing page](../../index.qmd), the first step is to allow comments on blog posts from GitHub users.
Stay tuned!
